### PR TITLE
Corporate proxy issue prevents connections between MS and GN

### PR DESCRIPTION
**Pull request by shadab-geo**
Updates the HTTP client to 4.5.13.

### CODE REVIEW

**Comment by tdipisa** [comment]
@offtherailz can you please spend some time reviewing this? @nmco it would be good, in my opinion, if you also can do the same to give your approval.

**Review by offtherailz — APPROVED** [review]
LGTM.

**Comment by MV88** [comment]
@tdipisa @offtherailz 

FYI 
this change broke [the build](https://github.com/geosolutions-it/MapStore2-C039/runs/5052415220?check_suite_focus=true#step:3:14463) on mapstore c039 project 
because it was not specifying the version of 
commons-httpclient

**Comment by nmco** [comment]
What do you mean @MV88? What version is missing?

**Comment by MV88** [comment]
@nmco see here https://github.com/geosolutions-it/MapStore2-C039/pull/220

as far as i understood
it was missing in the pom on the related project
and it was using the wrong one

**Comment by MV88** [comment]
@nmco 

Me @dromagnoli and @tdipisa have discussed about this as we are taking care of
no need for you to do anything about

**Pull request merged**
