### PR TITLE
[Fixes #9550] Show creator/editor in 'Edit properties'

### PR DESCRIPTION
**Pull request by afabiani**
Part of geosolutions-it/MapStore2#9550

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
Suggestions

- `editor` is misleading (and also `creator`, they both looks like some sort of roles), I'd suggest `createdBy` and `lastUpdatedBy` , consistent with `creation` and `lastUpdate` fields already present. 

Issues 
- [ ] I tried to create a resource as `user`, than make it editable by everyone and edit as `otheruser` but the editor still remain `user`, instead it should become `otheruser`
- [ ] This point is not respected. 
    > For existing resources we know only the owner, therefore creator/editor will be the same: this should be expected by the migration script itself

I'm admin and I can not see it in the `ShortResource`

image

While is visible for a new resource:

image

Anyway, I can say that while for creation we are sure about the role of the user, for last editing we are not sure. what do you think @tdipisa ?
About this point, as specified in my other review [here](https://github.com/geosolutions-it/geostore/pull/332) , installation should be as much as possible automatic, without bore the users (and us too) to run also update scripts. So I suggest to make it programmatically (or not do it at all, this information was not registered before, so it makes sense to not have it).

**Comment by offtherailz** [comment]
@tdipisa I wanted to suggest to not insert the "last updated by" information by checking the rule, because it is infact unknown.
Is better to not record this information at all and on the UI say last edited by "unknown"

**Comment by afabiani** [comment]
@offtherailz It is responsability of the client setting the editor. How can the backend know who did the changes?

**Comment by offtherailz** [comment]
@afabiani, I didn't followed this task from the beginning, but from my undestanding, this information is a typical "Created by", "Last modified by" metadata of the resource.
In every software I know, storing this kind of metadata (about who did what, when etc...) is responsability of the server, also for security reasons. Usually these kind of data are for administrators, and if someone did something wrong (e.g. maliciously) the normal user be able to change this information (e.g. inserting a fake name).

The server knows the user who does the operation, because it applies also security to it.

**Comment by tdipisa** [comment]
@afabiani 

>@tdipisa I wanted to suggest to not insert the "last updated by" information by checking the rule, because it is infact unknown.
Is better to not record this information at all and on the UI say last edited by "unknown"

As for the migration script it is ok for me if we persist only the creator. 

For the rest I think you can proceed fixing what reported [above](https://github.com/geosolutions-it/geostore/pull/333#pullrequestreview-1830289092) in the review of @offtherailz

**Comment by afabiani** [comment]
@tdipisa @offtherailz except for the name change suggested by Nali, the others changes have been done.

**Review by offtherailz — CHANGES_REQUESTED** [review]
Working perfectly :+1: 

- [x] It will conflict with https://github.com/geosolutions-it/geostore/pull/332 update script need to be merged.
- [ ] The creator update script is not present.

**Comment by tdipisa** [comment]
@afabiani can you please solve conflicts? Thank you.

**Comment by afabiani** [comment]
@offtherailz @tdipisa
 - conflicts fixed
 - sql script updated for the creator

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
