### PR TITLE
Upgrade of Spring dependency to a more recent version

### PR DESCRIPTION
**Pull request by mbarto**
Connected to #232 

The purpose of this work is to upgrade the Spring dependency to a more recent version, to enable implementing features that depend on Spring libraries that are not compatible with the actual 3.0.5 version.

Upgrading Spring required upgrading other libraries that depend on it. A short list:

| Library      | Old |New|
| ----------- | ----------- |--|
| Spring| 3.0.5|5.3.9|
| Spring-security| 3.0.5        |5.3.10|
| CXF| 2.3.2        |3.4.4|
| Hibernate|      3.3.2   |5.5.0|
| JPA| 1.0        |2.1|
| hibernate-generic-dao| 0.5.1        |1.3.0-SNAPSHOT|

After upgrading the libraries, all tests have been run (both offline and online) and passing. Some manual testing has been done too, including tests with MapStore.

Most of the changes in code are for:
 - changes in JPA 2.1 annotations
 - Password encoding moved to agecisecurity module
 - cleanup / fixing of REST apis produced media types, that were not working correctly anymore with upgraded libraries

**BREAKING CHANGES:**
 - csrf is enabled by default by the new spring security library, and this is conflicting with CXF endpoints, so this needs to be disabled in the geostore spring security configuration file (geostore-spring-security.xml):

```xml
<security:http auto-config="true" create-session="never" >
   ...
   <security:csrf disabled="true"/>
   ...
</security:http>
```

 - log4j and spring integration is automatic, and the related listener is not required anymore (and generates an error if not removed), so this needs to be removed from the application web.xml in depending projects (e.g. MapStore):

```xml
   <listener>
		<listener-class>org.springframework.web.util.Log4jConfigListener</listener-class>
   </listener>
```

### CODE REVIEW

**Comment by offtherailz** [comment]
@mbarto can you please merge with master, so you can run the actions for unit tests.
I committed them an our ago.

**Comment by mbarto** [comment]
> @mbarto can you please merge with master, so you can run the actions for unit tests.
> I committed them an our ago.

done

**Review by offtherailz — COMMENTED** [review]
LGTM

So we have actually synchronized master with 1.8-SNAPSHOT. Before merging we should update log4j too?

**Comment by mbarto** [comment]
> . Before merging we should update log4j too?

Not needed

**Comment by offtherailz** [comment]
> log4j and spring integration is automatic, and the related listener is not required anymore (and generates an error if not removed), so this needs to be removed from the application web.xml in depending projects (e.g. MapStore):

So I didn't understood this point.

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
as clarified with @mbarto I'm going to close my PR https://github.com/geosolutions-it/MapStore2/pull/7251 in favor on  #7172

**Pull request merged**
