### PR TITLE
[Fixes #9583] Unadvertised resources

### PR DESCRIPTION
**Pull request by afabiani**
Part of geosolutions-it/MapStore2#9583

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [ ] When I share a resource to everyone, it is listed despite is true or false. In fact the `advertised` flag doesn't look to make difference. From my understanding it should filter out the items on search/list services (e.g. extjs and more), while make the direct request to resource or resource data still available. 
    image
- [x] see my comment about default value. I tested and the values become anyway null. This causes a null pointer exception on requests like `get http://localhost:8081/rest/geostore/extjs/resource/52`

**Comment by offtherailz** [comment]
one hint. For testing MapStore with your changes I did the following (because master is pointing on latest GeoServer )
- build your pr geostore (using the proper profiles, i did it with `mvn clean install -Pall,extjs,postgres,h2` (not sure all these profile exists :smile: ) 
- run mapstore with `npm start`. It will build mapstore with geostore found in .m2 
- To configure the database in the instance started with `npm start` edit `java/web/src/main/resources/geostore-datasource-ovr.properties` as following before to run `npm start`

```
# Setup driver and dialect for PostgreSQL database
geostoreDataSource.driverClassName=org.postgresql.Driver
geostoreVendorAdapter.databasePlatform=org.hibernate.dialect.PostgreSQLDialect

# Connection parameters
geostoreDataSource.url=jdbc:postgresql://localhost:5432/geostore
geostoreDataSource.username=geostore
geostoreDataSource.password=geostore
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]=geostore

# Automatic create-update database mode
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=update

# Other options
geostoreVendorAdapter.generateDdl=true
geostoreVendorAdapter.showSql=false

```

**Comment by afabiani** [comment]
@offtherailz the resources should be still listed to their owners, at least this was a requirement. When you toggle `advertised` to `false`, are those resources listed to other users too?

**Comment by offtherailz** [comment]
Yes, during my test, that's what I noticed. 
In the screenshot I'm not logged (so I theoretically belong to group everyone) and I can see the records, marked with `advertised=true` or `false`. 
I can suggest start MapStore as described [here](https://github.com/geosolutions-it/geostore/pull/332#issuecomment-1898931824) to verify it by yourself.

**Comment by tdipisa** [comment]
@afabiani I think you can proceed fixing this according to the above review. I'm available if you have something to discuss.

**Comment by offtherailz** [comment]
please @afabiani if you are not able to replicate let me know, we can try together.

**Comment by afabiani** [comment]
@offtherailz the requested changes have been done

**Review by offtherailz — APPROVED** [review]
Works great :+1:

**Pull request merged**
