### PR TITLE
Audit Module Milestone 1

### PR DESCRIPTION
**Pull request by nmco**
Proposal: https://github.com/geosolutions-it/geostore/wiki/Proposal-%233:-adding-auditing-capabilities
Documentation: https://github.com/geosolutions-it/geostore/wiki/Auditing-Module

### CODE REVIEW

**Comment by Gnafu** [comment]
I did a test deploy, here's my comments:
- Use a prefix for the AUDITING_CONF variable, because it can exists another application that needs it: I suggest GEOSTORE_AUDITING_CONF
- The information dumped with the "remoteUser" property is too detailed (for example groups are fully dumped along the username, too much information): I suggest to break username, role and groups into three different properties.

**Comment by nmco** [comment]
Thank you for the comments, I will update the pull request.

**Comment by nmco** [comment]
Updated.

**Comment by tdipisa** [comment]
I tested locally on windows. Below you can find my feedbacks:

- could be useful to add a startTime and endTime into the Request report
- the footer xml never seems to be applied
- more description in the WIKI page should be added for each configuration property
- about the following point in the proposal have you any news? 
  "allow fine grained control over which REST end points should produce auditing information"
- There are some code conflict in the pull request that probably you can solve during the next commit.

**Comment by simboss** [comment]
I would leave point 3 aside for the time being.

**Comment by nmco** [comment]
Update as requested:
* add info: startTime, endTime, totalTime, responseContentType and responseLength
* add JVM shutdown hook with proper concurrency handling to add the footer

**Comment by tdipisa** [comment]
Your tests sound good for me, in any case there are some test failures involving the file paths:
- the configuration dir path from the auditing configuration (AuditingConfigurationTest.java:58)
- the template dir path (AuditingOutputTest.java:56)

I've tested on Windows. Can you check on that?

**Pull request merged**
